/* src/actions/index.js */
export const ITEM_LIST_RES = 'ITEM_LIST_RES';
export const ITEM_CREATE_REQ = 'ITEM_CREATE_REQ';
export const ITEM_CREATE_RES = 'ITEM_CREATE_RES';
export const ITEM_DELETE_REQ = 'ITEM_DELETE_REQ';
export const ITEM_DELETE_RES = 'ITEM_DELETE_RES';
export const ITEM_UPDATE_REQ = 'ITEM_UPDATE_REQ';
export const ITEM_UPDATE_RES = 'ITEM_UPDATE_RES';
export const GROUP_LIST_RES = 'GROUP_LIST_RES';
export const GROUP_CREATE_REQ = 'GROUP_CREATE_REQ';
export const GROUP_CREATE_RES = 'GROUP_CREATE_RES';
export const GROUP_DELETE_REQ = 'GROUP_DELETE_REQ';
export const GROUP_DELETE_RES = 'GROUP_DELETE_RES';
export const GROUP_UPDATE_REQ = 'GROUP_UPDATE_REQ';
export const GROUP_UPDATE_RES = 'GROUP_UPDATE_RES';
export const USER_CREATE_REQ = 'USER_CREATE_REQ';
export const USER_CREATE_RES = 'USER_CREATE_RES';
